baseURL = "https://blue-moon22.github.io"
languageCode = "en"
title = "Vicky's Blog"
theme = "hugo-nuo"
enableRobotsTXT = true
pygmentsuseclasses = true
PygmentsCodeFences = true
canonifyurls = true
publishDir = "docs"

# Disqus Username
# disqusShortname = "disqus_shortname"

# Google Analytics UA number
googleAnalytics = "UA-98918921-1"

# Copyright of your post
copyright = "© This post is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License，please give source if you likes to quote or reproduce."

# Initial site menu, you can extend menu with content.
[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"

# Add your own params here
[params]
  author = "Vicky Butt"
  avatar = "/images/dna.png"
  seotitle = "Vicky's Blog"
  subtitle = "Computational Biology PhD Student @ King's College London"
  description = ""
  paginate = 10

  # Choose your social networks
  email = "vicky.butt10@gmail.com"
  github = "blue-moon22"
  twitter = "vickybluemoon"
  linkedin = "victoria-butt-31b2aa126"
  # weibo = "weibo_username"
  # wechat= "/img/qrcode.jpg" # Replace with your wechat qrcode image
  # facebook = "facebook_username"
  # google = "googlplus_id_number"
  # instagram = "instagram_username"
  # youtube = "youtube_username"
  # vimeo = "vimeo_username"
  # medium = "medium_username"
  # quora = "quora_username"
  # pinterest = "pinterest_username"
  # dribbble = "dribbble_username"
  # behance = "behance_username"
  # jsfiddle = "jsfiddle_username"
  # codepen = "codepen_username"
  # zhihu = "zhihu_username"
  # douban = "douban_username"
  # bilibili = "bilibili_id_number"

  # Changyan Comments (China Only)
  #changyan = false
  #changyanId = "cyt3toRiB"
  #changyanConf = "prod_0908b1cb9a581501753cce1ed074dbe3"

  # Google Webmaster
  # https://www.google.com/webmasters/
  #googleSiteVerification = "_moDmnnBNVLBN1rzNxyGUGdPHE20YgbmrtzLIbxaWFc"

  # Bing Webmaster
  # https://www.bing.com/toolbox/webmaster/
  #msValidate = "22596E34341DD1D17D6022C44647E587"





