baseURL = "https://blue-moon22.github.io/index"
languageCode = "en"
title = "Vicky's Website"
theme = "hugo-nuo"
enableRobotsTXT = true
pygmentsuseclasses = true
PygmentsCodeFences = true
canonifyurls = true
publishDir = "docs"

# Disqus Username
# disqusShortname = "disqus_shortname"

# Google Analytics UA number
googleAnalytics = "UA-98918921-1"

# Copyright of your post
copyright = "© This post is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License，please give source if you likes to quote or reproduce."

# Initial site menu, you can extend menu with content.

[[menu.main]]
  name = "home"
  weight = -110
  identifier = "index"
  url = "/"

[[menu.main]]
  name = "Code"
  weight = -100
  identifier = "code"
  url = "/post/code/"

[[menu.main]]
  name = "Blog"
  weight = -90
  identifier = "blog"
  url = "/post/blog/"

# Add your own params here
[params]
  author = "Vicky Butt"
  avatar = "/images/dna.png"
  seotitle = "Vicky's Website"
  subtitle = "Data Science and Bioinformatics PhD Student @ King's College London"
  description = ""
  paginate = 10

  # Choose your social networks
  # email = "joe@bloggs.com"
  github = "blue-moon22"
  twitter = "vickybluemoon"
  linkedin = "victoria-butt-31b2aa126"